name: Run Intraday Script

#on: #[push]
#  schedule:
#    # Ejecutar todos los días hábiles a las 5 PM (UTC-3)
#    - cron: '0 20 * * 1-5'
    
jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run intraday script
        env:
          PPI_USER: ${{ secrets.PPI_USER }}
          PPI_PASS: ${{ secrets.PPI_PASS }}
        run: |
          python ./src/intraday.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update CSV from GitHub Action run"
      
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
