name: Run Intraday Script

on: #[push]
  schedule:
    # Ejecutar todos los días hábiles a las 5 PM (UTC-3)
    - cron: '0 20 * * 1-5'
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run intraday script
        env:
          PPI_USER: ${{ secrets.PPI_USER }}
          PPI_PASS: ${{ secrets.PPI_PASS }}
        run: |
          python ./src/intraday.py
